---
title: "Project 2"
author: "Morgan Bullock"
date: "3/15/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#load the mlbench package which has the BreastCancer data set
require(mlbench)

# if you don't have any required package, use the install.packages() command
# load the data set
data(BreastCancer)
# some algorithms don't like missing values, so remove rows with missing values
BreastCancer <- na.omit(BreastCancer) 
# remove the unique identifier, which is useless and would confuse the machine learning algorithms
BreastCancer$Id <- NULL 
# partition the data set for 80% training and 20% evaluation (adapted from ?randomForest)
set.seed(2)

ind <- sample(2, nrow(BreastCancer), replace = TRUE, prob=c(0.8, 0.2))


View(BreastCancer[ind == 1,])

View(BreastCancer[ind == 2,])

```



```{r}
#Support Vector machines
library(e1071)
mysvm <- svm(Class ~ ., BreastCancer[ind == 1,])
mysvm.pred <- predict(mysvm, BreastCancer[ind == 1,])
table(mysvm.pred,BreastCancer[ind == 1,]$Class)

#my results
#mysvm.pred  benign malignant
#  benign       343         7
#  malignant      9       176


```

```{r}

#Naive Bayes
#install.packages("klaR")

library(klaR)
mynb <- NaiveBayes(Class ~ ., BreastCancer[ind == 1,])
mynb.pred <- predict(mynb,BreastCancer[ind == 1,])
table(mynb.pred$class,BreastCancer[ind == 1,]$Class)

#My results
#           benign malignant
#  benign       344         2
#  malignant      8       181
```

```{r}

#Neural net
library(nnet)
mynnet <- nnet(Class ~ ., BreastCancer[ind == 1,], size=1)
mynnet.pred <- predict(mynnet,BreastCancer[ind == 1,],type="class")
table(mynnet.pred,BreastCancer[ind == 1,]$Class)


# My results
# weights:  83
#initial  value 375.458635 
#iter  10 value 55.788964
#iter  20 value 35.313641
#iter  30 value 26.745322
#iter  40 value 22.587759
#iter  50 value 22.223461
#iter  60 value 22.211660
#iter  70 value 22.205228
#iter  80 value 22.201648
#iter  90 value 22.200338
#iter 100 value 22.183252
#final  value 22.183252 
#stopped after 100 iterations
           
#mynnet.pred benign malignant
#  benign       349         1
#  malignant      3       182

```

```{r}
#Decision trees
library(rpart)
mytree <- rpart(Class ~ ., BreastCancer[ind == 1,])
#plot(mytree); text(mytree) 
#summary(mytree)
mytree.pred <- predict(mytree,BreastCancer[ind == 1,],type="class")
table(mytree.pred,BreastCancer[ind == 1,]$Class)

# My Results
# benign malignant
#  benign       343         2
#  malignant      9       181
```



```{r}
#Random Forests
library(randomForest)
myrf <- randomForest(Class ~ .,BreastCancer[ind == 1,])
myrf.pred <- predict(myrf, BreastCancer[ind == 1,])
table(myrf.pred, BreastCancer[ind == 1,]$Class)


#myrf.pred   benign malignant
#  benign       352         0
#  malignant      0       183
```

```{r}
#Regularised Discriminant Analysis
library(klaR)
myrda <- rda(Class ~ ., BreastCancer[ind == 1,])
myrda.pred <- predict(myrda, BreastCancer[ind == 1,])
table(myrda.pred$class,BreastCancer[ind == 1,]$Class)

#            benign malignant
#  benign       346         2
#  malignant      6       181
```


```{r}
#begin ensemble
#set malignant==1 Benign ==0
myrda.pred1<- data.frame(myrda.pred$class)
myrda.pred1<-ifelse(myrda.pred1=="malignant",1,0)
myrf.pred1<- data.frame(myrf.pred)
myrf.pred1<-ifelse(myrf.pred1=="malignant",1,0)
mytree.pred1<-data.frame(mytree.pred)
mytree.pred1<-ifelse(mytree.pred1=="malignant",1,0)
mynnet.pred1<-data.frame(mynnet.pred)
mynnet.pred1<-ifelse(mynnet.pred1=="malignant",1,0)
mynb.pred1<-data.frame(mynb.pred$class)
mynb.pred1<-ifelse(mynb.pred1=="malignant",1,0)
mysvm.pred1<-data.frame(mysvm.pred)
mysvm.pred1<-ifelse(mysvm.pred1=="malignant",1,0)

#build ensemble
ensembel.df<-data.frame(cbind(myrda.pred1, myrf.pred1, mytree.pred1, mynnet.pred1, mynb.pred1, mysvm.pred1))
sum<-rowSums(ensembel.df, na.rm = FALSE, dims = 1)
Class_majority<- ifelse(sum >3.5, "malignant", "benign")
ensembel.df1<-data.frame(cbind(ensembel.df, sum, Class_majority))

#test ensemble for test data
table(ensembel.df1$Class_majority,BreastCancer[ind == 1,]$Class)

# My results
#          benign malignant
#  benign       346         1
#  malignant      6       182



```


```{r}
#Predict Class with validation data set
myrda.predv <- predict(myrda, BreastCancer[ind == 2,])
myrf.predv <- predict(myrf, BreastCancer[ind == 2,])
mytree.predv <- predict(mytree,BreastCancer[ind == 2,],type="class")
mynnet.predv <- predict(mynnet,BreastCancer[ind == 2,],type="class")
mynb.predv <- predict(mynb,BreastCancer[ind == 2,])
mysvm.predv <- predict(mysvm, BreastCancer[ind == 2,])


#set up ensemble for validation
myrda.predv1<- data.frame(myrda.predv$class)
myrda.predv1<-ifelse(myrda.predv1=="malignant",1,0)

myrf.predv1<- data.frame(myrf.predv)
myrf.predv1<-ifelse(myrf.predv1=="malignant",1,0)

mytree.predv1<-data.frame(mytree.predv)
mytree.predv1<-ifelse(mytree.predv1=="malignant",1,0)

mynnet.predv1<-data.frame(mynnet.predv)
mynnet.predv1<-ifelse(mynnet.predv1=="malignant",1,0)

mynb.predv1<-data.frame(mynb.predv$class)
mynb.predv1<-ifelse(mynb.predv1=="malignant",1,0)

mysvm.predv1<-data.frame(mysvm.predv)
mysvm.predv1<-ifelse(mysvm.predv1=="malignant",1,0)

#build ensemble for validation
ensembel.v.df<-data.frame(cbind(myrda.predv1, myrf.predv1, mytree.predv1, mynnet.predv1, mynb.predv1, mysvm.predv1))
sum2<-rowSums(ensembel.v.df, na.rm = FALSE, dims = 1)
sum2<-data.frame(sum2)
Class_majority2<- ifelse(sum2 >3.5, "malignant", "benign")
Class_majority2<-data.frame(Class_majority2)
dim(sum2)
dim(Class_majority2)
dim(ensembel.v.df)

ensembel.v.df1<-data.frame(cbind(ensembel.v.df, sum2, Class_majority2))

View(ensembel.v.df1)

#test ensemble for validation data
table(ensembel.v.df1$sum2.1,BreastCancer[ind == 2,]$Class)


#  My results
#            benign malignant
#  benign        87         0
#  malignant      5        56

```




